server:
  port: 8081

jwt.secret: Z9hf=na/XPBcmh&hAEH?Akts6pgqJsE)Kwr*Kk7B96sJCLzrA4XJWCqcHQPL




eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone : Http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true

spring:
  application:
    name: auth-center
  datasource:
    url: jdbc:postgresql://localhost:5432/common
    username: postgres
    password: 19042001
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: validate