server:
  port: 8082

zuul:
  routes:
    auth-center:
      path: /login/**
      url: http://127.0.0.1:8081/
      sensitiveHeaders: Cookie,Set-Cookie
      stripPrefix: false

    api-v1:
      path: /v1/**
      url: http://127.0.0.1:8080/
      sensitiveHeaders: Cookie,Set-Cookie
      stripPrefix: true

    user-service:
      path: /user/**
      url: http://127.0.0.1:8083/
      sensitiveHeaders: Cookie,Set-Cookie
      stripPrefix: false



jwt.secret: Z9hf=na/XPBcmh&hAEH?Akts6pgqJsE)Kwr*Kk7B96sJCLzrA4XJWCqcHQPL

spring:
  application:
    name: api-gateway
  datasource:
    url: jdbc:postgresql://localhost:5432/common
    username: postgres
    password: 19042001
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: validate

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone : Http://localhost:8761/eureka/
  instance:
    hostname: localhost
#    prefer-ip-address: true